# Generated by Django 4.2.4 on 2025-01-03 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(max_length=100)),
                ('notification_message', models.CharField(max_length=100)),
                ('notification_date', models.DateField()),
                ('notification_time', models.TimeField()),
                ('notification_status', models.CharField(max_length=100)),
                ('notification_read', models.BooleanField()),
                ('notification_deleted', models.BooleanField()),
                ('notification_archived', models.BooleanField()),
                ('notification_priority', models.IntegerField()),
                ('notification_url', models.CharField(max_length=100)),
                ('notification_image', models.ImageField(upload_to='images/')),
                ('notification_attachment', models.FileField(upload_to='attachments/')),
                ('notification_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to=settings.AUTH_USER_MODEL)),
                ('notification_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
