FROM node:20-alpine

WORKDIR /app

COPY package.json /app/package.json

RUN npm install

COPY . /app/

EXPOSE 3000

RUN npm install -g nodemon

CMD ["nodemon", "--watch", ".", "--exec" , "npm start"]
