# Generated by Django 4.2.4 on 2025-01-03 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_alter_videoconference_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconference',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 18, 44, 7, 732472, tzinfo=datetime.timezone.utc)),
        ),
    ]
