# Generated by Django 4.2.4 on 2025-01-03 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_alter_videoconference_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconference',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 19, 3, 32, 50074, tzinfo=datetime.timezone.utc)),
        ),
    ]
