# Generated by Django 4.2.4 on 2025-01-03 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_alter_videoconference_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconference',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 20, 5, 25, 172061, tzinfo=datetime.timezone.utc)),
        ),
    ]
