# Generated by Django 4.2.4 on 2025-01-04 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_alter_videoconference_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconference',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 4, 19, 42, 18, 845658, tzinfo=datetime.timezone.utc)),
        ),
    ]
