# Generated by Django 4.2.4 on 2025-01-05 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0014_alter_videoconference_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconference',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 5, 29, 38, 137269, tzinfo=datetime.timezone.utc)),
        ),
    ]
