# Generated by Django 4.2.4 on 2025-01-05 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_alter_videoconference_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconference',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 22, 14, 13, 280001, tzinfo=datetime.timezone.utc)),
        ),
    ]
