# Generated by Django 4.2.4 on 2025-01-09 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0018_alter_videoconference_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconference',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 19, 31, 37, 383863, tzinfo=datetime.timezone.utc)),
        ),
    ]
