# Generated by Django 4.2.4 on 2025-01-10 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0020_alter_videoconference_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconference',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 20, 49, 22, 781111, tzinfo=datetime.timezone.utc)),
        ),
    ]
